import type { Metadata } from "next";
import { Julius_Sans_One } from "next/font/google"; // ← ✅ use Julius Sans One
import "./globals.css";

// Load the font
const juliusSansOne = Julius_Sans_One({
  variable: "--font-julius-sans-one",
  subsets: ["latin"],
  weight: "400", // Only 400 is available for this font
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={juliusSansOne.variable}>
      <body>{children}</body>
    </html>
  );
}
