import type { Metadata } from "next";
import { Libre_Bodoni } from "next/font/google";
import "./globals.css";
// pages/_app.js

const libreBodoni = Libre_Bodoni({
  variable: "--font-libre-bodoni",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={libreBodoni.variable}>
      <body>{children}</body>
    </html>
  );
}
